version: '3'

services:
  client:
    container_name: jazz-widget-client
    build: ./client
    image: jazz-widget-client-image
    expose:
      - "5000"
    dns:
      - 192.0.2.53
      
  server:
    container_name: jazz-widget-server
    build: ./server
    image: jazz-widget-server-image
    expose:
      - "4567"
    restart: always
    
  db:
    container_name: jazz-widget-mongo
    image: mongo:latest
    expose:
        - "27017"
    restart: always
      
  proxy:
    container_name: jazz-widget-proxy
    image: nginx:1.16.1
    ports:
      - '80:80'
      - '443:443'
      - '27017:27017'

    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs